apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: private-registry-key
      containers:
      - name: my-app
        image: nirdeshkumar02/my-app:latest  # Your Image URL <repository-name>/<image;tag>
        imagePullPolicy: Always
        ports:
          - containerPort: 3000