apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: product-catalog-service
        image: gcr.io/google-samples/microservices-demo/productcatalogservice
        ports:
        - containerPort: 3550
        env:
        - name: PORT 
          value: "3550"

---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  type: ClusterIP
  ports:
  - port: 3550
    targetPort: 3550

