apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shipping-service
        image: gcr.io/google-samples/microservices-demo/shippingservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT 
          value: "50051"

---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  selector:
    app: shippingservice
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051

