kind: Pod
apiVersion: v1
metadata:
  name: testpod1
  annotations: 
    description: This is a multicontainer pod environment
spec:
  containers: 
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]
    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu; sleep 5 ; done"]
