kind: ReplicaSet                                    
apiVersion: apps/v1                            
metadata:
  name: replication
spec:
  replicas: 2  
  selector:                  
    matchExpressions:                             # these must match the labels
      - {key: myname, operator: In, values: [Nirdesh, Saini]}
      - {key: env, operator: NotIn, values: [dev]}
  template:      
    metadata:
      name: replica-pod
      labels:              
        myname: Nirdesh
        env: prod
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Technical-Guftgu; sleep 5 ; done"]
