kind: Pod
apiVersion: v1
metadata:
  name: nodeselector-pod
  annotations: 
    description: This pod is the example of Node Selector, So that this pod only run on the specific type of node which satisfy the given condition.
  labels:
    class: pod
    type: nodeselector
    env: qa
spec:
  containers:
    - name: nodeselector-container
      image: ubuntu
      command: ["/bin/bash", "-c","while true; do echo Hey NodeSelector; sleep 5; done"]
  nodeSelector:
    hardware: t2.medium
